In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import roc_auc_score

In [2]:
data=pd.read_csv("kkkkk.csv")

In [3]:
data.head()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,area_business,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen
0,U001,0200769623,WAL-MAR corp,2019-12-27 00:00:00,2019.0,1.930283e+09,2019-12-15,20191215,20191215,20191230.0,USD,RV,1.0,NaN,31357.06,20191215.0,NAH4,1.930283e+09,0
1,U001,0200777735,NASH,2019-02-25 00:00:00,2019.0,1.928774e+09,2019-02-11,20190209,20190211,20190226.0,USD,RV,1.0,NaN,64325.57,20190211.0,NAA8,1.928774e+09,0
2,U001,CCU013,KRAFT F,2019-08-02 00:00:00,2019.0,1.929514e+09,2019-06-21,20190619,20190621,20190621.0,USD,RV,1.0,NaN,2269.31,20190621.0,NAX2,1.929514e+09,0
3,U001,0200793000,US corporation,2019-05-17 00:00:00,2019.0,1.929240e+09,2019-05-02,20190501,20190502,20190517.0,USD,RV,1.0,NaN,75708.78,20190502.0,NAA8,1.929240e+09,0
4,U001,0200769623,WAL-MAR co,2019-12-24 00:00:00,2019.0,1.930269e+09,2019-12-14,20191212,20191214,20191229.0,USD,RV,1.0,NaN,49429.64,20191214.0,NAH4,1.930269e+09,0

In [4]:
data.describe()

,buisness_year,doc_id,document_create_date,document_create_date.1,due_in_date,posting_id,area_business,total_open_amount,baseline_create_date,invoice_id,isOpen
count,50000.000000,5.000000e+04,5.000000e+04,5.000000e+04,5.000000e+04,50000.0,0.0,5.000000e+04,5.000000e+04,4.999300e+04,50000.000000
mean,2019.201380,2.012053e+09,2.019247e+07,2.019250e+07,2.019267e+07,1.0,NaN,3.211643e+04,2.019250e+07,2.011005e+09,0.077980
std,0.401035,2.899804e+08,3.876596e+03,3.864099e+03,3.888985e+03,0.0,NaN,3.993505e+04,3.865498e+03,2.761310e+08,0.268143
min,2019.000000,1.928502e+09,2.018123e+07,2.018123e+07,2.018123e+07,1.0,NaN,6.800000e-01,2.018122e+07,1.928502e+09,0.000000
25%,2019.000000,1.929232e+09,2.019042e+07,2.019042e+07,2.019051e+07,1.0,NaN,4.682677e+03,2.019042e+07,1.929232e+09,0.000000
50%,2019.000000,1.929809e+09,2.019081e+07,2.019081e+07,2.019082e+07,1.0,NaN,1.744501e+04,2.019081e+07,1.929809e+09,0.000000
75%,2019.000000,1.930392e+09,2.019112e+07,2.019112e+07,2.019121e+07,1.0,NaN,4.676173e+04,2.019112e+07,1.930392e+09,0.000000
max,2020.000000,9.500000e+09,2.020052e+07,2.020052e+07,2.020071e+07,1.0,NaN,1.506681e+06,2.020052e+07,2.960635e+09,1.000000

In [5]:
data.shape

(50000, 19)

In [6]:
data.isnull().sum()

business_code                 0
cust_number                   0
name_customer                 0
clear_date                 3899
buisness_year                 0
doc_id                        0
posting_date                  0
document_create_date          0
document_create_date.1        0
due_in_date                   0
invoice_currency              0
document type                 0
posting_id                    0
area_business             50000
total_open_amount             0
baseline_create_date          0
cust_payment_terms            0
invoice_id                    7
isOpen                        0
dtype: int64

In [7]:
data.drop(columns=['area_business'],inplace=True)

In [8]:
data.isnull().sum()

business_code                0
cust_number                  0
name_customer                0
clear_date                3899
buisness_year                0
doc_id                       0
posting_date                 0
document_create_date         0
document_create_date.1       0
due_in_date                  0
invoice_currency             0
document type                0
posting_id                   0
total_open_amount            0
baseline_create_date         0
cust_payment_terms           0
invoice_id                   7
isOpen                       0
dtype: int64

In [9]:
# check the presence of null data.
[col for col in data.columns if data[col].isnull().sum() > 0]

['clear_date', 'invoice_id']

In [10]:
X_train = data.loc[data['clear_date'].notnull()]
X_train.shape

(46101, 18)

In [11]:
X_test = data.loc[data.clear_date.isnull()]
X_test.shape

(3899, 18)

In [12]:
X_train.isnull().sum()

business_code             0
cust_number               0
name_customer             0
clear_date                0
buisness_year             0
doc_id                    0
posting_date              0
document_create_date      0
document_create_date.1    0
due_in_date               0
invoice_currency          0
document type             0
posting_id                0
total_open_amount         0
baseline_create_date      0
cust_payment_terms        0
invoice_id                7
isOpen                    0
dtype: int64

In [13]:
X_test.isnull().sum()

business_code                0
cust_number                  0
name_customer                0
clear_date                3899
buisness_year                0
doc_id                       0
posting_date                 0
document_create_date         0
document_create_date.1       0
due_in_date                  0
invoice_currency             0
document type                0
posting_id                   0
total_open_amount            0
baseline_create_date         0
cust_payment_terms           0
invoice_id                   0
isOpen                       0
dtype: int64

In [14]:
X_train.loc[X_train.invoice_id.isnull()]

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen
3785,CA02,0140104429,COSTCO us,2019-07-16 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190227,20190309.0,CAD,X2,1.0,42393.60,20190227.0,CA10,NaN,0
7827,CA02,0140104409,LOB trust,2019-05-22 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190314,20190324.0,CAD,X2,1.0,542.00,20190314.0,CA10,NaN,0
21266,CA02,0140106054,TREE systems,2019-05-06 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190208,20190218.0,CAD,X2,1.0,29170.80,20190208.0,CA10,NaN,0
28041,CA02,0140106054,TREE llc,2019-05-09 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190225,20190307.0,CAD,X2,1.0,5896.80,20190225.0,CA10,NaN,0
32774,CA02,0140104225,SAVE-ON- in,2019-05-02 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190220,20190302.0,CAD,X2,1.0,3620.16,20190220.0,CA10,NaN,0
33446,CA02,0140104429,COSTCO foundation,2019-05-14 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190311,20190321.0,CAD,X2,1.0,5353.20,20190311.0,CA10,NaN,0
41371,CA02,0140104409,LOB co,2019-05-31 00:00:00,2019.0,9.500000e+09,2019-03-29,20190329,20190314,20190324.0,CAD,X2,1.0,13595.04,20190314.0,CA10,NaN,0

In [15]:

X_train, X_validation = train_test_split(X_train,test_size=.3,shuffle=False)
X_train.shape,X_validation.shape

((32270, 18), (13831, 18))

In [16]:
X_train.shape,X_test.shape,X_validation.shape

((32270, 18), (3899, 18), (13831, 18))

In [17]:
X_train.head()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen
0,U001,0200769623,WAL-MAR corp,2019-12-27 00:00:00,2019.0,1.930283e+09,2019-12-15,20191215,20191215,20191230.0,USD,RV,1.0,31357.06,20191215.0,NAH4,1.930283e+09,0
1,U001,0200777735,NASH,2019-02-25 00:00:00,2019.0,1.928774e+09,2019-02-11,20190209,20190211,20190226.0,USD,RV,1.0,64325.57,20190211.0,NAA8,1.928774e+09,0
2,U001,CCU013,KRAFT F,2019-08-02 00:00:00,2019.0,1.929514e+09,2019-06-21,20190619,20190621,20190621.0,USD,RV,1.0,2269.31,20190621.0,NAX2,1.929514e+09,0
3,U001,0200793000,US corporation,2019-05-17 00:00:00,2019.0,1.929240e+09,2019-05-02,20190501,20190502,20190517.0,USD,RV,1.0,75708.78,20190502.0,NAA8,1.929240e+09,0
4,U001,0200769623,WAL-MAR co,2019-12-24 00:00:00,2019.0,1.930269e+09,2019-12-14,20191212,20191214,20191229.0,USD,RV,1.0,49429.64,20191214.0,NAH4,1.930269e+09,0

In [18]:
X_train['clear_date'] = pd.to_datetime(X_train['clear_date'])
X_train['posting_date'] = pd.to_datetime(X_train['posting_date'])
X_train['document_create_date'] = pd.to_datetime(X_train['document_create_date'], format='%Y%m%d') 
X_train['document_create_date.1'] = pd.to_datetime(X_train['document_create_date.1'], format='%Y%m%d')
X_train['due_in_date'] = pd.to_datetime(X_train['due_in_date'], format='%Y%m%d')
X_train['baseline_create_date'] = pd.to_datetime(X_train['baseline_create_date'], format='%Y%m%d')
X_train.head()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen
0,U001,0200769623,WAL-MAR corp,2019-12-27,2019.0,1.930283e+09,2019-12-15,2019-12-15,2019-12-15,2019-12-30,USD,RV,1.0,31357.06,2019-12-15,NAH4,1.930283e+09,0
1,U001,0200777735,NASH,2019-02-25,2019.0,1.928774e+09,2019-02-11,2019-02-09,2019-02-11,2019-02-26,USD,RV,1.0,64325.57,2019-02-11,NAA8,1.928774e+09,0
2,U001,CCU013,KRAFT F,2019-08-02,2019.0,1.929514e+09,2019-06-21,2019-06-19,2019-06-21,2019-06-21,USD,RV,1.0,2269.31,2019-06-21,NAX2,1.929514e+09,0
3,U001,0200793000,US corporation,2019-05-17,2019.0,1.929240e+09,2019-05-02,2019-05-01,2019-05-02,2019-05-17,USD,RV,1.0,75708.78,2019-05-02,NAA8,1.929240e+09,0
4,U001,0200769623,WAL-MAR co,2019-12-24,2019.0,1.930269e+09,2019-12-14,2019-12-12,2019-12-14,2019-12-29,USD,RV,1.0,49429.64,2019-12-14,NAH4,1.930269e+09,0

In [19]:
X_train['DELAY']=X_train['clear_date'] - X_train['due_in_date']

In [20]:
X_train.tail()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen,DELAY
32265,U001,200785971,SYSCO in,2019-04-12,2019.0,1.929039e+09,2019-03-27,2019-03-27,2019-03-27,2019-04-11,USD,RV,1.0,21243.86,2019-03-27,NAA8,1.929039e+09,0,1 days
32266,U001,0200741174,M B in,2019-12-19,2019.0,1.930148e+09,2019-11-14,2019-11-13,2019-11-14,2019-12-16,USD,RV,1.0,41444.22,2019-11-14,NA32,1.930148e+09,0,3 days
32267,U001,0200795490,HY - corporation,2019-09-20,2019.0,1.929829e+09,2019-09-04,2019-09-05,2019-09-04,2019-09-19,USD,RV,1.0,95039.71,2019-09-04,NAA8,1.929829e+09,0,1 days
32268,U001,0200792293,UNIFIE associates,2019-10-03,2019.0,1.929880e+09,2019-09-17,2019-09-17,2019-09-17,2019-10-02,USD,RV,1.0,24180.29,2019-09-17,NAA8,1.929880e+09,0,1 days
32269,U001,0200704858,WAKE corp,2019-09-30,2019.0,1.929864e+09,2019-09-12,2019-09-11,2019-09-12,2019-09-27,USD,RV,1.0,53351.32,2019-09-12,NAA8,1.929864e+09,0,3 days

In [48]:
X_train.dtypes

business_code                      object
cust_number                        object
name_customer                      object
clear_date                 datetime64[ns]
buisness_year                     float64
doc_id                            float64
posting_date               datetime64[ns]
document_create_date       datetime64[ns]
document_create_date.1     datetime64[ns]
due_in_date                datetime64[ns]
invoice_currency                   object
document type                      object
posting_id                        float64
total_open_amount                 float64
baseline_create_date       datetime64[ns]
cust_payment_terms                 object
invoice_id                        float64
isOpen                              int64
DELAY                     timedelta64[ns]
dtype: object

SyntaxError: invalid syntax (<ipython-input-22-a35077a93b18>, line 1)

In [33]:
X_train.sort_values(['document_create_date.1'],inplace=True)
X_train.reset_index(inplace=True,drop=True)
X_train.head()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen,DELAY
0,U001,0200769623,WAL-MAR corp,2019-01-11,2019.0,1.928543e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,45645.00,2018-12-30,NAH4,1.928543e+09,0,-3 days
1,U013,0140103335,PARAM in,2019-01-23,2019.0,1.991820e+09,2018-12-30,2018-12-26,2018-12-30,2019-01-29,USD,RV,1.0,1574.71,2018-12-30,NAVE,1.991820e+09,0,-6 days
2,U001,0200707822,PUBLI trust,2019-01-14,2019.0,1.928534e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,130434.25,2018-12-30,NAA8,1.928534e+09,0,0 days
3,U001,0200726979,BJ'S in,2019-01-15,2019.0,1.928540e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,59.80,2018-12-30,NAA8,1.928540e+09,0,1 days
4,U001,0200148860,DOLLA co,2019-01-14,2019.0,1.928544e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,1285.12,2018-12-30,NAA8,1.928544e+09,0,0 days
5,U001,0200759878,SA foundation,2019-01-15,2019.0,1.928533e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,14380.16,2018-12-30,NAH4,1.928533e+09,0,1 days
6,CA02,0140105847,GORDON F systems,2019-01-14,2019.0,2.960521e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-12,CAD,RV,1.0,66459.30,2019-01-02,CA10,2.960521e+09,0,2 days
7,U001,0200769623,WAL-MAR foundation,2019-01-09,2019.0,1.928538e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,44346.56,2018-12-30,NAH4,1.928538e+09,0,-5 days
8,U001,0200769623,WAL-MAR co,2019-01-15,2019.0,1.928537e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,32021.70,2018-12-30,NAH4,1.928537e+09,0,1 days
9,U001,0200769623,WAL-MAR associates,2019-01-09,2019.0,1.928540e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,70372.34,2018-12-30,NAH4,1.928540e+09,0,-5 days
10,U001,0200881076,ALBERT systems,2019-01-14,2019.0,1.928538e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,1092.61,2018-12-30,NAA8,1.928538e+09,0,0 days
11,U001,0200744019,TARG,2019-01-11,2019.0,1.928544e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,3185.78,2018-12-30,NAA8,1.928544e+09,0,-3 days
12,U001,0200762301,C&S WH in,2019-01-15,2019.0,1.928543e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,26125.08,2018-12-30,NAC6,1.928543e+09,0,1 days
13,U001,0200769623,WAL-MAR corp,2019-01-10,2019.0,1.928543e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,34293.38,2018-12-30,NAH4,1.928543e+09,0,-4 days
14,U001,0200769623,WAL-MAR associates,2019-01-09,2019.0,1.928541e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,33736.93,2018-12-30,NAH4,1.928541e+09,0,-5 days
15,U001,0200769623,WAL-MAR llc,2019-01-18,2019.0,1.928535e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,9522.21,2018-12-30,NAH4,1.928535e+09,0,4 days
16,U001,0200744019,TARG foundation,2019-01-11,2019.0,1.928542e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,18804.46,2018-12-30,NAA8,1.928542e+09,0,-3 days
17,U001,0200622385,US,2019-01-18,2019.0,1.928541e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,65531.73,2018-12-30,NAA8,1.928541e+09,0,4 days
18,U001,0200769623,WAL-MAR,2019-01-09,2019.0,1.928538e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,39118.11,2018-12-30,NAH4,1.928538e+09,0,-5 days
19,U001,0200769623,WAL-MAR trust,2019-01-09,2019.0,1.928533e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,7552.27,2018-12-30,NAH4,1.928533e+09,0,-5 days
20,U001,0200719300,SYSTEMS foundation,2019-01-15,2019.0,1.928534e+09,2018-12-30,2018-12-31,2018-12-30,2019-01-14,USD,RV,1.0,256.00,2018-12-30,NAA8,1.928534e+09,0,1 days
21,U001,0200769623,WAL-MAR us,2019-01-14,2019.0,1.928535e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,3408.73,2018-12-30,NAH4,1.928535e+09,0,0 days
22,U001,0200769623,WAL-MAR corporation,2019-01-15,2019.0,1.928541e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,5445.24,2018-12-30,NAH4,1.928541e+09,0,1 days
23,U001,0200769623,WAL-MAR trust,2019-01-10,2019.0,1.928543e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,12428.72,2018-12-30,NAH4,1.928543e+09,0,-4 days
24,U001,0200769623,WAL-MAR in,2019-01-10,2019.0,1.928544e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,40978.46,2018-12-30,NAH4,1.928544e+09,0,-4 days
25,U001,0200769623,WAL-MAR associates,2019-01-09,2019.0,1.928539e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,55416.62,2018-12-30,NAH4,1.928539e+09,0,-5 days
26,U001,0200769623,WAL-MAR in,2019-01-10,2019.0,1.928543e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,1764.66,2018-12-30,NAH4,1.928543e+09,0,-4 days
27,U001,0200726979,BJ'S llc,2019-01-15,2019.0,1.928540e+09,2018-12-30,2018-12-29,2018-12-30,2019-01-14,USD,RV,1.0,137.84,2018-12-30,NAA8,1.928540e+09,0,1 days
28,U001,0100033558,TRI- foundation,2019-01-07,2019.0,1.928533e+09,2018-12-30,2018-12-31,2018-12-30,2019-02-03,USD,RV,1.0,16058.00,2018-12-30,NAG2,1.928533e+09,0,-27 days
29,U001,0200780383,MEIJ corp,2019-01-18,2019.0,1.928544e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-14,USD,RV,1.0,101268.28,2018-12-30,NAA8,1.928544e+09,0,4 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32240,U001,0200762301,C&S WH in,2020-03-13,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-05-01,USD,RV,1.0,18682.27,2020-02-26,NAGD,1.930571e+09,0,-49 days
32241,U001,0200739006,AL,2020-03-11,2020.0,1.930549e+09,2020-02-26,2020-02-20,2020-02-26,2020-03-12,USD,RV,1.0,22505.33,2020-02-26,NAA8,1.930549e+09,0,-1 days
32242,U001,0200769623,WAL-MAR,2020-03-16,2020.0,1.930566e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,842.06,2020-02-26,NAH4,1.930566e+09,0,4 days
32243,U013,0100055606,ALVARE systems,2020-03-30,2020.0,1.991838e+09,2020-02-26,2020-02-24,2020-02-26,2020-03-27,USD,RV,1.0,35701.64,2020-02-26,NAVE,1.991838e+09,0,3 days
32244,CA02,0140106293,ATLANT in,2020-03-16,2020.0,2.960616e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-16,CAD,RV,1.0,75433.42,2020-03-06,CA10,2.960616e+09,0,0 days
32245,U001,0140142846,MONDE us,2020-04-29,2020.0,1.930568e+09,2020-02-26,2020-02-26,2020-02-26,2020-04-26,USD,RV,1.0,68832.40,2020-02-26,NACB,1.930568e+09,0,3 days
32246,U001,0200418007,AM associates,2020-03-12,2020.0,1.930551e+09,2020-02-26,2020-02-21,2020-02-26,2020-05-01,USD,RV,1.0,1478.40,2020-02-26,NAGD,1.930551e+09,0,-50 days
32247,U001,0200936373,SUPE us,2020-03-12,2020.0,1.930561e+09,2020-02-26,2020-02-24,2020-02-26,2020-03-12,USD,RV,1.0,22416.59,2020-02-26,NAA8,1.930561e+09,0,0 days
32248,U001,0200936373,SUPE co,2020-03-12,2020.0,1.930561e+09,2020-02-26,2020-02-24,2020-02-26,2020-03-12,USD,RV,1.0,57555.49,2020-02-26,NAA8,1.930561e+09,0,0 days
32249,U001,0200799367,MCL corp,2020-03-12,2020.0,1.930553e+09,2020-02-26,2020-02-21,2020-02-26,2020-03-12,USD,RV,1.0,9612.45,2020-02-26,NAA8,1.930553e+09,0,0 days
32250,U001,0200769623,WAL-MAR associates,2020-03-09,2020.0,1.930570e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,27769.16,2020-02-26,NAH4,1.930570e+09,0,-3 days
32251,U001,0200793568,SUPE foundation,2020-03-16,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,623.81,2020-02-26,NAA8,1.930571e+09,0,4 days
32252,U001,0200769623,WAL-MAR corporation,2020-03-17,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,18323.99,2020-02-26,NAH4,1.930571e+09,0,5 days
32253,U001,0200769623,WAL-MAR corp,2020-03-09,2020.0,1.930566e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,14274.87,2020-02-26,NAH4,1.930566e+09,0,-3 days
32254,U001,0200752302,KROGER corporation,2020-03-12,2020.0,1.930565e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,14431.04,2020-02-26,NAA8,1.930565e+09,0,0 days
32255,U001,0200711029,WEGMAN in,2020-03-12,2020.0,1.930572e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,51198.23,2020-02-26,NAA8,1.930572e+09,0,0 days
32256,U001,0200704045,RA,2020-03-12,2020.0,1.930568e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,17580.25,2020-02-26,NAA8,1.930568e+09,0,0 days
32257,U001,0200729290,KROGER foundation,2020-03-13,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,124011.40,2020-02-26,NAA8,1.930571e+09,0,1 days
32258,U001,0200769623,WAL-MAR corp,2020-03-09,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,39472.99,2020-02-26,NAH4,1.930571e+09,0,-3 days
32259,U001,0200759878,SA llc,2020-03-13,2020.0,1.930570e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,31097.98,2020-02-26,NAH4,1.930570e+09,0,1 days
32260,U001,0200769623,WAL-MAR,2020-03-09,2020.0,1.930567e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,661.11,2020-02-26,NAH4,1.930567e+09,0,-3 days
32261,CA02,0140106408,WAL-M corporation,2020-03-13,2020.0,2.960614e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-08,CAD,RV,1.0,154736.81,2020-02-27,CA10,2.960614e+09,0,5 days
32262,U001,0200592182,DECA trust,2020-03-02,2020.0,1.930571e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-10,USD,RV,1.0,1600.08,2020-02-16,NAM4,1.930571e+09,0,-8 days
32263,U001,0200769623,WAL-MAR corporation,2020-03-09,2020.0,1.930566e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,13522.55,2020-02-26,NAH4,1.930566e+09,0,-3 days
32264,U001,0100031704,DELHAIZE,2020-03-12,2020.0,1.930550e+09,2020-02-26,2020-02-20,2020-02-26,2020-03-12,USD,RV,1.0,3680.07,2020-02-26,NAA8,1.930550e+09,0,0 days
32265,U001,0200759878,SA,2020-03-13,2020.0,1.930564e+09,2020-02-26,2020-02-24,2020-02-26,2020-03-12,USD,RV,1.0,13603.02,2020-02-26,NAH4,1.930564e+09,0,1 days
32266,U001,0200726979,BJ'S us,2020-03-12,2020.0,1.930566e+09,2020-02-26,2020-02-25,2020-02-26,2020-03-12,USD,RV,1.0,485.13,2020-02-26,NAA8,1.930566e+09,0,0 days
32267,U001,0200793568,SUPE systems,2020-03-13,2020.0,1.930570e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-12,USD,RV,1.0,19907.99,2020-02-26,NAA8,1.930570e+09,0,1 days
32268,U001,0200744707,PERFOR,2020-03-16,2020.0,1.930574e+09,2020-02-27,2020-02-26,2020-02-27,2020-03-13,USD,RV,1.0,39408.22,2020-02-27,NAA8,1.930574e+09,0,3 days
32269,U001,0200759878,SA in,2020-03-16,2020.0,1.930566e+09,2020-02-27,2020-02-25,2020-02-27,2020-03-13,USD,RV,1.0,35147.76,2020-02-27,NAH4,1.930566e+09,0,3 days

In [47]:
# X_train.loc(np.where(X_train['document_create_date.1'] <= X_train['posting_date']))
# if(X_train['document_create_date.1'] < X_train['posting_date'] == True):
#     print("a")
    
diff = X_train['posting_date'] - X_train['document_create_date.1']

if diff <  pd.Timedelta('0 day'):
    print("Column_A is greater than Column_B")
    # Column_A is greater than Column_B
else:
    print("Column_B is greater than Column_A")
    # Column_B is greater than Column_A

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [52]:
X_train[X_train['document_create_date.1'] < X_train['posting_date']]

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen,DELAY
2891,CA02,0140106054,TREE systems,2019-05-06,2019.0,9.500000e+09,2019-03-29,2019-03-29,2019-02-08,2019-02-18,CAD,X2,1.0,29170.8,2019-02-08,CA10,NaN,0,77 days
4233,CA02,0140106054,TREE llc,2019-05-09,2019.0,9.500000e+09,2019-03-29,2019-03-29,2019-02-25,2019-03-07,CAD,X2,1.0,5896.8,2019-02-25,CA10,NaN,0,63 days
4336,CA02,0140104429,COSTCO us,2019-07-16,2019.0,9.500000e+09,2019-03-29,2019-03-29,2019-02-27,2019-03-09,CAD,X2,1.0,42393.6,2019-02-27,CA10,NaN,0,129 days
5689,CA02,0140104409,LOB trust,2019-05-22,2019.0,9.500000e+09,2019-03-29,2019-03-29,2019-03-14,2019-03-24,CAD,X2,1.0,542.0,2019-03-14,CA10,NaN,0,59 days

In [53]:
X_train[X_train['document_create_date.1'] < X_train['posting_date']]

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen,DELAY
6,CA02,0140105847,GORDON F systems,2019-01-14,2019.0,2.960521e+09,2018-12-30,2018-12-30,2018-12-30,2019-01-12,CAD,RV,1.0,66459.30,2019-01-02,CA10,2.960521e+09,0,2 days
96,CA02,0140104440,SO,2019-01-16,2019.0,2.960521e+09,2018-12-31,2018-12-31,2018-12-31,2019-01-12,CAD,RV,1.0,89597.99,2019-01-02,CA10,2.960521e+09,0,4 days
129,CA02,0140104440,SO foundation,2019-01-17,2019.0,2.960521e+09,2019-01-02,2019-01-02,2019-01-02,2019-01-13,CAD,RV,1.0,319238.63,2019-01-03,CA10,2.960521e+09,0,4 days
160,CA02,0140104225,SAVE-ON- llc,2019-01-16,2019.0,2.960521e+09,2019-01-02,2019-01-02,2019-01-02,2019-01-21,CAD,RV,1.0,3655.55,2019-01-11,CA10,2.960521e+09,0,-5 days
164,CA02,0140106372,G T in,2019-01-18,2019.0,2.960521e+09,2019-01-02,2019-01-02,2019-01-02,2019-01-14,CAD,RV,1.0,13861.74,2019-01-04,CA10,2.960521e+09,0,4 days
185,CA02,0140104409,LOB associates,2019-01-18,2019.0,2.960521e+09,2019-01-02,2019-01-02,2019-01-02,2019-01-14,CAD,RV,1.0,79376.35,2019-01-04,CA10,2.960521e+09,0,4 days
208,CA02,0140104429,COSTCO associates,2019-01-14,2019.0,2.960521e+09,2019-01-03,2019-01-03,2019-01-03,2019-01-14,CAD,RV,1.0,112627.80,2019-01-04,CA10,2.960521e+09,0,0 days
229,CA02,0140106293,ATLANT in,2019-01-21,2019.0,2.960521e+09,2019-01-03,2019-01-03,2019-01-03,2019-01-21,CAD,RV,1.0,36916.81,2019-01-11,CA10,2.960521e+09,0,0 days
302,CA02,0140104409,LOB co,2019-01-21,2019.0,2.960520e+09,2019-01-04,2019-01-04,2019-01-04,2019-01-24,CAD,RV,1.0,11909.66,2019-01-14,CA10,2.960520e+09,0,-3 days
318,CA02,0140104440,SO corp,2019-01-21,2019.0,2.960521e+09,2019-01-04,2019-01-04,2019-01-04,2019-01-18,CAD,RV,1.0,18073.10,2019-01-08,CA10,2.960521e+09,0,3 days
340,CA02,0140118168,RONALD systems,2019-02-04,2019.0,2.960521e+09,2019-01-04,2019-01-04,2019-01-04,2019-02-04,CAD,RV,1.0,18120.00,2019-01-05,CA30,2.960521e+09,0,0 days
359,CA02,0140104429,COSTCO us,2019-02-01,2019.0,2.960521e+09,2019-01-04,2019-01-04,2019-01-04,2019-01-21,CAD,RV,1.0,41231.75,2019-01-11,CA10,2.960521e+09,0,11 days
374,CA02,0140105686,SYSC foundation,2019-01-31,2019.0,2.960520e+09,2019-01-05,2019-01-05,2019-01-05,2019-01-25,CAD,RV,1.0,45503.55,2019-01-15,CA10,2.960520e+09,0,6 days
382,CA02,0140106408,WAL-M trust,2019-01-25,2019.0,2.960521e+09,2019-01-05,2019-01-05,2019-01-05,2019-01-16,CAD,RV,1.0,44104.02,2019-01-06,CA10,2.960521e+09,0,9 days
446,CA02,0140105686,SYSC systems,2019-01-24,2019.0,2.960520e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-20,CAD,RV,1.0,17123.50,2019-01-10,CA10,2.960520e+09,0,4 days
466,CA02,0140104409,LOB systems,2019-02-08,2019.0,2.960521e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-28,CAD,RV,1.0,21989.82,2019-01-18,CA10,2.960521e+09,0,11 days
479,CA02,0140105678,SAPUTO corp,2019-01-25,2019.0,2.960519e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-18,CAD,RV,1.0,22496.70,2019-01-08,CA10,2.960519e+09,0,7 days
490,CA02,0140104429,COSTCO corporation,2019-01-23,2019.0,2.960521e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-18,CAD,RV,1.0,14538.07,2019-01-08,CA10,2.960521e+09,0,5 days
492,CA02,0140104429,COSTCO,2019-01-31,2019.0,2.960522e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-26,CAD,RV,1.0,99410.63,2019-01-16,CA10,2.960522e+09,0,5 days
495,CA02,0140105686,SYSC llc,2019-01-24,2019.0,2.960521e+09,2019-01-07,2019-01-07,2019-01-07,2019-01-19,CAD,RV,1.0,12993.00,2019-01-09,CA10,2.960521e+09,0,5 days
504,CA02,CCU013,KRAFT F in,2019-03-01,2019.0,2.960520e+09,2019-01-07,2019-01-07,2019-01-07,2019-02-17,CAD,RV,1.0,22120.41,2019-02-17,NAX2,2.960520e+09,0,12 days
518,CA02,0140104409,LOB co,2019-01-21,2019.0,2.960522e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,86566.23,2019-01-10,CA10,2.960522e+09,0,1 days
521,CA02,0140105847,GORDON F corp,2019-01-21,2019.0,2.960522e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,8652.49,2019-01-10,CA10,2.960522e+09,0,1 days
526,CA02,0140105686,SYSC corporation,2019-01-31,2019.0,2.960520e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-27,CAD,RV,1.0,534.50,2019-01-17,CA10,2.960520e+09,0,4 days
532,CA02,0140104472,MARTIN llc,2019-01-23,2019.0,2.960522e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,11875.28,2019-01-10,CA10,2.960522e+09,0,3 days
536,CA02,0140104423,METRO associates,2019-02-19,2019.0,2.960520e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,29933.86,2019-01-10,CA10,2.960520e+09,0,30 days
547,CA02,0140105686,SYSC llc,2019-01-24,2019.0,2.960521e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,15432.25,2019-01-10,CA10,2.960521e+09,0,4 days
573,CA02,0140105686,SYSC,2019-01-31,2019.0,2.960520e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-27,CAD,RV,1.0,9812.85,2019-01-17,CA10,2.960520e+09,0,4 days
581,CA02,0140104409,LOB co,2019-02-08,2019.0,2.960521e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-27,CAD,RV,1.0,18596.16,2019-01-17,CA10,2.960521e+09,0,12 days
586,CA02,0140104423,METRO foundation,2019-01-18,2019.0,2.960520e+09,2019-01-08,2019-01-08,2019-01-08,2019-01-20,CAD,RV,1.0,69104.40,2019-01-10,CA10,2.960520e+09,0,-2 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31894,CA02,0140104440,SO corp,2020-03-16,2020.0,2.960616e+09,2020-02-22,2020-02-22,2020-02-22,2020-03-08,CAD,RV,1.0,11604.94,2020-02-27,CA10,2.960616e+09,0,8 days
31903,CA02,0140104429,COSTCO corporation,2020-03-06,2020.0,2.960616e+09,2020-02-22,2020-02-22,2020-02-22,2020-03-06,CAD,RV,1.0,4572.18,2020-02-25,CA10,2.960616e+09,0,0 days
31924,CA02,0140104285,BUY-,2020-03-16,2020.0,2.960616e+09,2020-02-23,2020-02-24,2020-02-23,2020-03-13,CAD,RV,1.0,26300.30,2020-03-03,CA10,2.960616e+09,0,3 days
31934,CA02,0140104429,COSTCO in,2020-03-23,2020.0,2.960616e+09,2020-02-23,2020-02-24,2020-02-23,2020-03-13,CAD,RV,1.0,83533.49,2020-03-03,CA10,2.960616e+09,0,10 days
31938,CA02,0140104409,LOB systems,2020-03-06,2020.0,2.960616e+09,2020-02-23,2020-02-23,2020-02-23,2020-03-05,CAD,RV,1.0,153714.53,2020-02-24,CA10,2.960616e+09,0,1 days
31950,CA02,0140104331,CORE-M in,2020-03-04,2020.0,2.960615e+09,2020-02-23,2020-02-23,2020-02-23,2020-03-13,CAD,RV,1.0,24043.81,2020-03-03,CA10,2.960615e+09,0,-9 days
31972,CA02,0140105686,SYSC foundation,2020-03-12,2020.0,2.960616e+09,2020-02-24,2020-02-24,2020-02-24,2020-03-07,CAD,RV,1.0,5402.54,2020-02-26,CA10,2.960616e+09,0,5 days
31973,CA02,0140104429,COSTCO foundation,2020-03-23,2020.0,2.960616e+09,2020-02-24,2020-02-24,2020-02-24,2020-03-06,CAD,RV,1.0,1506.48,2020-02-25,CA10,2.960616e+09,0,17 days
31983,CA02,0100054234,11078 corporation,2020-03-04,2020.0,2.960616e+09,2020-02-24,2020-02-24,2020-02-24,2020-03-07,CAD,RV,1.0,11169.36,2020-02-26,CA10,2.960616e+09,0,-3 days
32008,CA02,0100034823,ZARCO,2020-03-03,2020.0,2.960616e+09,2020-02-24,2020-02-24,2020-02-24,2020-03-07,CAD,RV,1.0,16372.34,2020-02-26,CA10,2.960616e+09,0,-4 days
32034,CA02,0140105704,CASSE co,2020-03-09,2020.0,2.960616e+09,2020-02-24,2020-02-24,2020-02-24,2020-03-07,CAD,RV,1.0,27852.02,2020-02-26,CA10,2.960616e+09,0,2 days
32062,CA02,0140106408,WAL-M corp,2020-03-16,2020.0,2.960617e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-07,CAD,RV,1.0,6069.00,2020-02-26,CA10,2.960617e+09,0,9 days
32075,CA02,0140105686,SYSC,2020-03-19,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-14,CAD,RV,1.0,66168.86,2020-03-04,CA10,2.960616e+09,0,5 days
32077,CA02,0140104429,COSTCO trust,2020-03-23,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-15,CAD,RV,1.0,31086.72,2020-03-05,CA10,2.960616e+09,0,8 days
32078,CA02,0140104440,SO foundation,2020-03-17,2020.0,2.960617e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-07,CAD,RV,1.0,77357.73,2020-02-26,CA10,2.960617e+09,0,10 days
32080,CA02,0140104440,SO foundation,2020-03-18,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-09,CAD,RV,1.0,214103.44,2020-02-28,CA10,2.960616e+09,0,9 days
32087,CA02,0140104423,METRO trust,2020-03-09,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-08,CAD,RV,1.0,181563.94,2020-02-27,CA10,2.960616e+09,0,1 days
32088,CA02,0100054993,CENTRAL in,2020-03-23,2020.0,2.960617e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-10,CAD,RV,1.0,5346.25,2020-02-29,CA10,2.960617e+09,0,13 days
32108,CA02,0140105847,GORDON F llc,2020-03-16,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-15,CAD,RV,1.0,57223.74,2020-03-05,CA10,2.960616e+09,0,1 days
32113,CA02,0140106408,WAL-M corp,2020-03-12,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-07,CAD,RV,1.0,52820.07,2020-02-26,CA10,2.960616e+09,0,5 days
32139,CA02,0140105847,GORDON F,2020-03-09,2020.0,2.960616e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-07,CAD,RV,1.0,25243.00,2020-02-26,CA10,2.960616e+09,0,2 days
32141,CA02,0140104409,LOB in,2020-03-09,2020.0,2.960617e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-08,CAD,RV,1.0,14754.30,2020-02-27,CA10,2.960617e+09,0,1 days
32157,CA02,0140106408,WAL-M in,2020-03-19,2020.0,2.960617e+09,2020-02-25,2020-02-25,2020-02-25,2020-03-07,CAD,RV,1.0,6258.79,2020-02-26,CA10,2.960617e+09,0,12 days
32169,CA02,0140104440,SO systems,2020-03-17,2020.0,2.960614e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-08,CAD,RV,1.0,94030.25,2020-02-27,CA10,2.960614e+09,0,9 days
32190,CA02,0140106260,EMP corporation,2020-03-12,2020.0,2.960617e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-09,CAD,RV,1.0,19960.87,2020-02-28,CA10,2.960617e+09,0,3 days
32199,CA02,0140104429,COSTCO trust,2020-03-23,2020.0,2.960617e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-09,CAD,RV,1.0,1100.69,2020-02-28,CA10,2.960617e+09,0,14 days
32206,CA02,0140106408,WAL-M systems,2020-03-13,2020.0,2.960617e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-08,CAD,RV,1.0,53843.33,2020-02-27,CA10,2.960617e+09,0,5 days
32208,CA02,0140104440,SO llc,2020-03-18,2020.0,2.960616e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-08,CAD,RV,1.0,74779.15,2020-02-27,CA10,2.960616e+09,0,10 days
32244,CA02,0140106293,ATLANT in,2020-03-16,2020.0,2.960616e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-16,CAD,RV,1.0,75433.42,2020-03-06,CA10,2.960616e+09,0,0 days
32261,CA02,0140106408,WAL-M corporation,2020-03-13,2020.0,2.960614e+09,2020-02-26,2020-02-26,2020-02-26,2020-03-08,CAD,RV,1.0,154736.81,2020-02-27,CA10,2.960614e+09,0,5 days

In [ ]:
X_train[X_train['posting_date'] < X_train['baseline_create_date']]

In [56]:
constant_features = [
    feat for feat in X_train.columns if X_train[feat].std() == 0
]

TypeError: could not convert string to float: 'U001'