#Data Loading

In [6]:
import numpy as np
import pandas as pd
import random
from sklearn.datasets import load_boston
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [7]:

inv_num=[]
inv_day=[]
inv_amt=[]
reg=[]
cust=[]
clear=[]
due=[]
for i in range(200):
  inv_num.append('1001'+str(random.randint(100,900)))
  inv_day.append(str(random.randint(1,30))+'-'+'05'+'-2020')
  due.append(str(random.randint(1,30))+str(random.randint(5,7))+'2020.0')
  clear.append(str(random.randint(1,30))+str(random.randint(5,7))+'2020.0')
  inv_amt.append(str(random.randint(1,1000))+'.'+str(random.randint(1,99)))
  reg.append(np.random.choice(['NA','SA','NZ','LATAM']))
  cust.append(np.random.choice(['Hooli','EndFrame','Pieper_chat','GROW_MORE','Riot','Laxmi_Funds_25days']))

In [8]:
df_1=pd.DataFrame({'INVOICE_NUMBER':inv_num,'Creation_date':inv_day,'Amount($)':inv_amt,'Region':reg,'Due_date':due,'CLEARING_DATE':clear,'CUSTOMER_NAME':cust,'Business_Area':reg})

In [9]:
df_1.head()

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area
0,1001174,24-05-2020,290.98,NZ,362020.0,1062020.0,Laxmi_Funds_25days,NZ
1,1001735,26-05-2020,755.73,NA,2052020.0,172020.0,Laxmi_Funds_25days,NA
2,1001719,15-05-2020,4.55,NZ,872020.0,1652020.0,Laxmi_Funds_25days,NZ
3,1001524,1-05-2020,224.61,NZ,872020.0,462020.0,GROW_MORE,NZ
4,1001427,14-05-2020,999.97,SA,1272020.0,1872020.0,EndFrame,SA

In [10]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
INVOICE_NUMBER    200 non-null object
Creation_date     200 non-null object
Amount($)         200 non-null object
Region            200 non-null object
Due_date          200 non-null object
CLEARING_DATE     200 non-null object
CUSTOMER_NAME     200 non-null object
Business_Area     200 non-null object
dtypes: object(8)
memory usage: 12.6+ KB

In [12]:
df_1.isnull()

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
170,False,False,False,False,False,False,False,False
171,False,False,False,False,False,False,False,False
172,False,False,False,False,False,False,False,False
173,False,False,False,False,False,False,False,False
174,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False
176,False,False,False,False,False,False,False,False
177,False,False,False,False,False,False,False,False
178,False,False,False,False,False,False,False,False
179,False,False,False,False,False,False,False,False
180,False,False,False,False,False,False,False,False
181,False,False,False,False,False,False,False,False
182,False,False,False,False,False,False,False,False
183,False,False,False,False,False,False,False,False
184,False,False,False,False,False,False,False,False
185,False,False,False,False,False,False,False,False
186,False,False,False,False,False,False,False,False
187,False,False,False,False,False,False,False,False
188,False,False,False,False,False,False,False,False
189,False,False,False,False,False,False,False,False
190,False,False,False,False,False,False,False,False
191,False,False,False,False,False,False,False,False
192,False,False,False,False,False,False,False,False
193,False,False,False,False,False,False,False,False
194,False,False,False,False,False,False,False,False
195,False,False,False,False,False,False,False,False
196,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False

In [13]:
df_1.isnull().any()

INVOICE_NUMBER    False
Creation_date     False
Amount($)         False
Region            False
Due_date          False
CLEARING_DATE     False
CUSTOMER_NAME     False
Business_Area     False
dtype: bool

#Sanity / Pre Processing

validating the Dtype

In [14]:
df_1['Creation_date'].head()

0    24-05-2020
1    26-05-2020
2    15-05-2020
3     1-05-2020
4    14-05-2020
Name: Creation_date, dtype: object

In [18]:
df_1['Creation_date']=pd.to_datetime(df_1['Creation_date'],format='%Y%m%d')

ValueError: time data '24-05-2020' does not match format '%Y%m%d' (match)

In [19]:
df_1['Creation_date']=pd.to_datetime(df_1['Creation_date'],format='%d-%m-%Y')

In [20]:
df_1['Creation_date'].head()

0   2020-05-24
1   2020-05-26
2   2020-05-15
3   2020-05-01
4   2020-05-14
Name: Creation_date, dtype: datetime64[ns]

In [21]:
df_1['CLEARING_DATE']

0      1062020.0
1       172020.0
2      1652020.0
3       462020.0
4      1872020.0
5       572020.0
6      2852020.0
7      2972020.0
8      2152020.0
9      2962020.0
10     2862020.0
11      472020.0
12      972020.0
13      672020.0
14     1672020.0
15     1952020.0
16     2862020.0
17     2352020.0
18     2952020.0
19      272020.0
20     1672020.0
21      552020.0
22      262020.0
23      572020.0
24     1552020.0
25     1252020.0
26      272020.0
27      352020.0
28     1472020.0
29     2252020.0
         ...
170    3052020.0
171     472020.0
172     952020.0
173     352020.0
174     962020.0
175    2752020.0
176     572020.0
177    3062020.0
178    1952020.0
179    2552020.0
180    1772020.0
181    2052020.0
182     462020.0
183     262020.0
184     162020.0
185    2572020.0
186     672020.0
187    2752020.0
188    2762020.0
189     352020.0
190    3062020.0
191    1862020.0
192     152020.0
193     452020.0
194    2352020.0
195     862020.0
196    1662020.0
197    2762020.0
198    1962020.0
199    1572020.0
Name: CLEARING_DATE, Length: 200, dtype: object

In [22]:
df_1['CLEARING_DATE']=pd.to_datetime(df_1['CLEARING_DATE'].astype('float'),format='%d%m%Y')
df_1['Due_date']=pd.to_datetime(df_1['Due_date'].astype('float'),format='%d%m%Y')

TypeError: 'float' object is unsliceable

In [23]:
df_1['CLEARING_DATE'].head()

0    1062020.0
1     172020.0
2    1652020.0
3     462020.0
4    1872020.0
Name: CLEARING_DATE, dtype: object

In [24]:
df_1['Due_date'].head()

0     362020.0
1    2052020.0
2     872020.0
3     872020.0
4    1272020.0
Name: Due_date, dtype: object

#Train Test Split

In [28]:
#df_1 <- Train

In [29]:
df_1['delay']=(df_1['CLEARING_DATE']-df_1['Due_date']).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [30]:
df_1.sort_values(by='CREATION_DATE',inplace=True) #use document_date_norm.1

KeyError: 'CREATION_DATE'

In [31]:
df_1.shape

(200, 8)

In [32]:
test1=df_1.tail(40)
val=test1.iloc[:20,:]

In [33]:
test1=test1.tail(20)

In [34]:
val.shape,test1.shape

((20, 8), (20, 8))

In [35]:
set(val.index).intersection(set(test1.index))

set()

In [36]:
r=len(df_1)-40

In [37]:
df_1=df_1.head(r)
len(df_1)

160

#EDA (Data Analysis)

In [38]:
df_1['INVOICE_NUMBER'].nunique()

150

In [39]:
df_1.shape[0]

160

In [40]:
df_1['Region'].unique()

array(['NZ', 'NA', 'SA', 'LATAM'], dtype=object)

check that sufficient data is there ...

In [41]:
df_1['Region'].value_counts()

SA       45
LATAM    41
NZ       40
NA       34
Name: Region, dtype: int64

In [42]:
df_1.shape

(160, 8)

In [43]:
df_1[df_1['CLEARING_DATE']<df_1['Creation_date']].shape

TypeError: '<' not supported between instances of 'str' and 'int'

In [44]:
df_1[df_1['Due_date']<df_1['Creation_date']].shape

TypeError: '<' not supported between instances of 'str' and 'int'

In [45]:
df_1=df_1.drop(index=df_1[df_1['CLEARING_DATE']<df_1['Creation_date']].index)
df_1=df_1.drop(index=df_1[df_1['Due_date']<df_1['Creation_date']].index)

TypeError: '<' not supported between instances of 'str' and 'int'

In [46]:
df_1.shape[0]

160

In [47]:
df_1['Creation_date'].max()

Timestamp('2020-05-30 00:00:00')

In [48]:
df_1['Creation_date'].min()

Timestamp('2020-05-01 00:00:00')

In [49]:
df_1['delay']=(df_1['CLEARING_DATE']-df_1['Due_date']).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [50]:
df_1['delay']

KeyError: 'delay'

In [51]:
df_1.loc[:,['CUSTOMER_NAME','Creation_date','Due_date','CLEARING_DATE','delay']]

C:\Users\KIIT\Anaconda3\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

          CUSTOMER_NAME Creation_date   Due_date CLEARING_DATE  delay
0    Laxmi_Funds_25days    2020-05-24   362020.0     1062020.0    NaN
1    Laxmi_Funds_25days    2020-05-26  2052020.0      172020.0    NaN
2    Laxmi_Funds_25days    2020-05-15   872020.0     1652020.0    NaN
3             GROW_MORE    2020-05-01   872020.0      462020.0    NaN
4              EndFrame    2020-05-14  1272020.0     1872020.0    NaN
5             GROW_MORE    2020-05-15  2672020.0      572020.0    NaN
6           Pieper_chat    2020-05-14   752020.0     2852020.0    NaN
7              EndFrame    2020-05-02  1462020.0     2972020.0    NaN
8                  Riot    2020-05-04   252020.0     2152020.0    NaN
9                  Riot    2020-05-20  2952020.0     2962020.0    NaN
10             EndFrame    2020-05-08   552020.0     2862020.0    NaN
11             EndFrame    2020-05-23  1052020.0      472020.0    NaN
12                Hooli    2020-05-05  2862020.0      972020.0    NaN
13                 Riot    2020-05-10  1362020.0      672020.0    NaN
14                 Riot    2020-05-05  1062020.0     1672020.0    NaN
15            GROW_MORE    2020-05-30  2762020.0     1952020.0    NaN
16            GROW_MORE    2020-05-02  3072020.0     2862020.0    NaN
17                Hooli    2020-05-26  1552020.0     2352020.0    NaN
18          Pieper_chat    2020-05-19  2162020.0     2952020.0    NaN
19            GROW_MORE    2020-05-22  2872020.0      272020.0    NaN
20                Hooli    2020-05-20  1072020.0     1672020.0    NaN
21          Pieper_chat    2020-05-15  1862020.0      552020.0    NaN
22             EndFrame    2020-05-08  2372020.0      262020.0    NaN
23            GROW_MORE    2020-05-22   752020.0      572020.0    NaN
24   Laxmi_Funds_25days    2020-05-10  2352020.0     1552020.0    NaN
25   Laxmi_Funds_25days    2020-05-14  1462020.0     1252020.0    NaN
26                 Riot    2020-05-21  1452020.0      272020.0    NaN
27            GROW_MORE    2020-05-12  2072020.0      352020.0    NaN
28                Hooli    2020-05-09   352020.0     1472020.0    NaN
29             EndFrame    2020-05-27  2052020.0     2252020.0    NaN
..                  ...           ...        ...           ...    ...
130               Hooli    2020-05-07   152020.0     1462020.0    NaN
131           GROW_MORE    2020-05-12  1972020.0     2752020.0    NaN
132         Pieper_chat    2020-05-14  2752020.0      772020.0    NaN
133            EndFrame    2020-05-18   162020.0     2652020.0    NaN
134               Hooli    2020-05-30  2162020.0     1952020.0    NaN
135                Riot    2020-05-20   672020.0      572020.0    NaN
136               Hooli    2020-05-24   952020.0     1062020.0    NaN
137            EndFrame    2020-05-15  2252020.0      152020.0    NaN
138               Hooli    2020-05-19  2972020.0     2562020.0    NaN
139         Pieper_chat    2020-05-07  1952020.0     2772020.0    NaN
140           GROW_MORE    2020-05-12   762020.0     2772020.0    NaN
141           GROW_MORE    2020-05-05  2362020.0     1552020.0    NaN
142               Hooli    2020-05-26  1572020.0     1872020.0    NaN
143  Laxmi_Funds_25days    2020-05-27  1252020.0     1572020.0    NaN
144            EndFrame    2020-05-13   262020.0      552020.0    NaN
145         Pieper_chat    2020-05-11  2362020.0      952020.0    NaN
146  Laxmi_Funds_25days    2020-05-16   572020.0     2862020.0    NaN
147           GROW_MORE    2020-05-22   162020.0     1762020.0    NaN
148         Pieper_chat    2020-05-16  1372020.0     1972020.0    NaN
149         Pieper_chat    2020-05-23  1552020.0     2172020.0    NaN
150                Riot    2020-05-09  3062020.0      752020.0    NaN
151  Laxmi_Funds_25days    2020-05-28  1662020.0     1472020.0    NaN
152            EndFrame    2020-05-26  2562020.0     1452020.0    NaN
153            EndFrame    2020-05-11  1772020.0      172020.0    NaN
154            EndFrame    2020-05-08  1262020.0     2872020.0    NaN
155                Riot    2020-05-30  1252020.0      362020.0    NaN
156         Pieper_chat    2020-05-12  2962020.0      172020.0    NaN
157         Pieper_chat    2020-05-07  2272020.0     1362020.0    NaN
158               Hooli    2020-05-07  2862020.0      772020.0    NaN
159                Riot    2020-05-18  2452020.0     1862020.0    NaN

[160 rows x 5 columns]

In [52]:
df_1['Weekday']=df_1['Creation_date'].dt.weekday

In [53]:
def catog_delay(x):
  if x<=0:
    return 0
  else: 
    return 1

In [54]:
df_1['delay'].describe()

KeyError: 'delay'

mapper

In [55]:
df_1

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area,Weekday
0,1001174,2020-05-24,290.98,NZ,362020.0,1062020.0,Laxmi_Funds_25days,NZ,6
1,1001735,2020-05-26,755.73,NA,2052020.0,172020.0,Laxmi_Funds_25days,NA,1
2,1001719,2020-05-15,4.55,NZ,872020.0,1652020.0,Laxmi_Funds_25days,NZ,4
3,1001524,2020-05-01,224.61,NZ,872020.0,462020.0,GROW_MORE,NZ,4
4,1001427,2020-05-14,999.97,SA,1272020.0,1872020.0,EndFrame,SA,3
5,1001519,2020-05-15,6.5,LATAM,2672020.0,572020.0,GROW_MORE,LATAM,4
6,1001109,2020-05-14,418.98,LATAM,752020.0,2852020.0,Pieper_chat,LATAM,3
7,1001772,2020-05-02,734.81,LATAM,1462020.0,2972020.0,EndFrame,LATAM,5
8,1001880,2020-05-04,219.80,SA,252020.0,2152020.0,Riot,SA,0
9,1001152,2020-05-20,487.41,LATAM,2952020.0,2962020.0,Riot,LATAM,2
10,1001160,2020-05-08,497.80,SA,552020.0,2862020.0,EndFrame,SA,4
11,1001681,2020-05-23,725.31,LATAM,1052020.0,472020.0,EndFrame,LATAM,5
12,1001680,2020-05-05,432.26,SA,2862020.0,972020.0,Hooli,SA,1
13,1001856,2020-05-10,794.95,NA,1362020.0,672020.0,Riot,NA,6
14,1001504,2020-05-05,734.17,SA,1062020.0,1672020.0,Riot,SA,1
15,1001643,2020-05-30,170.58,NZ,2762020.0,1952020.0,GROW_MORE,NZ,5
16,1001789,2020-05-02,196.39,SA,3072020.0,2862020.0,GROW_MORE,SA,5
17,1001787,2020-05-26,873.36,SA,1552020.0,2352020.0,Hooli,SA,1
18,1001243,2020-05-19,950.27,NA,2162020.0,2952020.0,Pieper_chat,NA,1
19,1001629,2020-05-22,378.32,NA,2872020.0,272020.0,GROW_MORE,NA,4
20,1001559,2020-05-20,986.82,SA,1072020.0,1672020.0,Hooli,SA,2
21,1001598,2020-05-15,22.77,NA,1862020.0,552020.0,Pieper_chat,NA,4
22,1001354,2020-05-08,767.53,LATAM,2372020.0,262020.0,EndFrame,LATAM,4
23,1001893,2020-05-22,641.43,NZ,752020.0,572020.0,GROW_MORE,NZ,4
24,1001180,2020-05-10,629.91,NZ,2352020.0,1552020.0,Laxmi_Funds_25days,NZ,6
25,1001216,2020-05-14,262.16,LATAM,1462020.0,1252020.0,Laxmi_Funds_25days,LATAM,3
26,1001133,2020-05-21,740.64,NA,1452020.0,272020.0,Riot,NA,3
27,1001339,2020-05-12,389.40,SA,2072020.0,352020.0,GROW_MORE,SA,1
28,1001246,2020-05-09,274.51,SA,352020.0,1472020.0,Hooli,SA,5
29,1001227,2020-05-27,653.33,NZ,2052020.0,2252020.0,EndFrame,NZ,2
...,...,...,...,...,...,...,...,...,...
130,1001453,2020-05-07,171.47,NA,152020.0,1462020.0,Hooli,NA,3
131,1001613,2020-05-12,434.90,SA,1972020.0,2752020.0,GROW_MORE,SA,1
132,1001233,2020-05-14,470.65,SA,2752020.0,772020.0,Pieper_chat,SA,3
133,1001705,2020-05-18,38.30,LATAM,162020.0,2652020.0,EndFrame,LATAM,0
134,1001632,2020-05-30,501.76,LATAM,2162020.0,1952020.0,Hooli,LATAM,5
135,1001291,2020-05-20,247.6,LATAM,672020.0,572020.0,Riot,LATAM,2
136,1001313,2020-05-24,67.33,NZ,952020.0,1062020.0,Hooli,NZ,6
137,1001160,2020-05-15,356.47,LATAM,2252020.0,152020.0,EndFrame,LATAM,4
138,1001776,2020-05-19,309.99,LATAM,2972020.0,2562020.0,Hooli,LATAM,1
139,1001771,2020-05-07,218.80,LATAM,1952020.0,2772020.0,Pieper_chat,LATAM,3
140,1001389,2020-05-12,274.25,NZ,762020.0,2772020.0,GROW_MORE,NZ,1
141,1001602,2020-05-05,248.1,NZ,2362020.0,1552020.0,GROW_MORE,NZ,1
142,1001525,2020-05-26,531.99,NA,1572020.0,1872020.0,Hooli,NA,1
143,1001761,2020-05-27,55.22,NZ,1252020.0,1572020.0,Laxmi_Funds_25days,NZ,2
144,1001615,2020-05-13,139.25,LATAM,262020.0,552020.0,EndFrame,LATAM,2
145,1001888,2020-05-11,456.82,SA,2362020.0,952020.0,Pieper_chat,SA,0
146,1001249,2020-05-16,674.95,LATAM,572020.0,2862020.0,Laxmi_Funds_25days,LATAM,5
147,1001679,2020-05-22,908.59,SA,162020.0,1762020.0,GROW_MORE,SA,4
148,1001104,2020-05-16,648.50,NA,1372020.0,1972020.0,Pieper_chat,NA,5
149,1001892,2020-05-23,837.59,LATAM,1552020.0,2172020.0,Pieper_chat,LATAM,5
150,1001430,2020-05-09,196.72,NA,3062020.0,752020.0,Riot,NA,5
151,1001618,2020-05-28,854.80,NZ,1662020.0,1472020.0,Laxmi_Funds_25days,NZ,3
152,1001193,2020-05-26,332.45,NZ,2562020.0,1452020.0,EndFrame,NZ,1
153,1001791,2020-05-11,593.40,NA,1772020.0,172020.0,EndFrame,NA,0
154,1001242,2020-05-08,258.7,NZ,1262020.0,2872020.0,EndFrame,NZ,4
155,1001732,2020-05-30,480.91,NZ,1252020.0,362020.0,Riot,NZ,5
156,1001668,2020-05-12,552.77,NA,2962020.0,172020.0,Pieper_chat,NA,1
157,1001383,2020-05-07,293.41,LATAM,2272020.0,1362020.0,Pieper_chat,LATAM,3
158,1001336,2020-05-07,426.75,SA,2862020.0,772020.0,Hooli,SA,3
159,1001779,2020-05-18,901.10,LATAM,2452020.0,1862020.0,Riot,LATAM,0

In [56]:
plt.figure(figsize=(20,10))
sns.lineplot(df_1['Creation_date'], df_1['delay'])
plt.xlabel("Create Date")
plt.ylabel("Delay")
plt.title("Create Date vs Delay")
plt.show()

AttributeError: module 'seaborn' has no attribute 'lineplot'

In [57]:
plt.figure(figsize=(20,10))
sns.lineplot(df_1['Due_date'].dt.dayofweek, df_1['delay'])
plt.xlabel("Due Week Day")
plt.ylabel("Delay")
plt.title("Week Day vs Delay")
plt.show()

AttributeError: module 'seaborn' has no attribute 'lineplot'

In [58]:
plt.figure(figsize=(20,10))
sns.lineplot(df_1['Due_date'].dt.day, df_1['delay'])
plt.xlabel("Day")
plt.ylabel("Delay")
plt.title("Day vs Delay")
plt.show()

AttributeError: module 'seaborn' has no attribute 'lineplot'

#Feature Engineering

Mapper

In [59]:
map_cust=df_1.groupby("CUSTOMER_NAME")['delay'].mean().to_dict()

KeyError: 'Column not found: delay'

In [60]:
map_cust

NameError: name 'map_cust' is not defined

In [61]:
df_1['Cust Mean Delay']=df_1['CUSTOMER_NAME'].map(map_cust)
df_1

NameError: name 'map_cust' is not defined

In [62]:
val.columns

Index(['INVOICE_NUMBER', 'Creation_date', 'Amount($)', 'Region', 'Due_date',
       'CLEARING_DATE', 'CUSTOMER_NAME', 'Business_Area'],
      dtype='object')

In [63]:
val['Cust Mean Delay']=val['CUSTOMER_NAME'].map(map_cust)
val['Cust Mean Delay'][val['Cust Mean Delay'].isnull()]= val['delay'].mean()
val

NameError: name 'map_cust' is not defined

In [64]:
df_1['Week_is_3']=np.where(df_1['Due_date'].dt.dayofweek==3,1,0)

AttributeError: Can only use .dt accessor with datetimelike values

In [65]:
df_1

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area,Weekday
0,1001174,2020-05-24,290.98,NZ,362020.0,1062020.0,Laxmi_Funds_25days,NZ,6
1,1001735,2020-05-26,755.73,NA,2052020.0,172020.0,Laxmi_Funds_25days,NA,1
2,1001719,2020-05-15,4.55,NZ,872020.0,1652020.0,Laxmi_Funds_25days,NZ,4
3,1001524,2020-05-01,224.61,NZ,872020.0,462020.0,GROW_MORE,NZ,4
4,1001427,2020-05-14,999.97,SA,1272020.0,1872020.0,EndFrame,SA,3
5,1001519,2020-05-15,6.5,LATAM,2672020.0,572020.0,GROW_MORE,LATAM,4
6,1001109,2020-05-14,418.98,LATAM,752020.0,2852020.0,Pieper_chat,LATAM,3
7,1001772,2020-05-02,734.81,LATAM,1462020.0,2972020.0,EndFrame,LATAM,5
8,1001880,2020-05-04,219.80,SA,252020.0,2152020.0,Riot,SA,0
9,1001152,2020-05-20,487.41,LATAM,2952020.0,2962020.0,Riot,LATAM,2
10,1001160,2020-05-08,497.80,SA,552020.0,2862020.0,EndFrame,SA,4
11,1001681,2020-05-23,725.31,LATAM,1052020.0,472020.0,EndFrame,LATAM,5
12,1001680,2020-05-05,432.26,SA,2862020.0,972020.0,Hooli,SA,1
13,1001856,2020-05-10,794.95,NA,1362020.0,672020.0,Riot,NA,6
14,1001504,2020-05-05,734.17,SA,1062020.0,1672020.0,Riot,SA,1
15,1001643,2020-05-30,170.58,NZ,2762020.0,1952020.0,GROW_MORE,NZ,5
16,1001789,2020-05-02,196.39,SA,3072020.0,2862020.0,GROW_MORE,SA,5
17,1001787,2020-05-26,873.36,SA,1552020.0,2352020.0,Hooli,SA,1
18,1001243,2020-05-19,950.27,NA,2162020.0,2952020.0,Pieper_chat,NA,1
19,1001629,2020-05-22,378.32,NA,2872020.0,272020.0,GROW_MORE,NA,4
20,1001559,2020-05-20,986.82,SA,1072020.0,1672020.0,Hooli,SA,2
21,1001598,2020-05-15,22.77,NA,1862020.0,552020.0,Pieper_chat,NA,4
22,1001354,2020-05-08,767.53,LATAM,2372020.0,262020.0,EndFrame,LATAM,4
23,1001893,2020-05-22,641.43,NZ,752020.0,572020.0,GROW_MORE,NZ,4
24,1001180,2020-05-10,629.91,NZ,2352020.0,1552020.0,Laxmi_Funds_25days,NZ,6
25,1001216,2020-05-14,262.16,LATAM,1462020.0,1252020.0,Laxmi_Funds_25days,LATAM,3
26,1001133,2020-05-21,740.64,NA,1452020.0,272020.0,Riot,NA,3
27,1001339,2020-05-12,389.40,SA,2072020.0,352020.0,GROW_MORE,SA,1
28,1001246,2020-05-09,274.51,SA,352020.0,1472020.0,Hooli,SA,5
29,1001227,2020-05-27,653.33,NZ,2052020.0,2252020.0,EndFrame,NZ,2
...,...,...,...,...,...,...,...,...,...
130,1001453,2020-05-07,171.47,NA,152020.0,1462020.0,Hooli,NA,3
131,1001613,2020-05-12,434.90,SA,1972020.0,2752020.0,GROW_MORE,SA,1
132,1001233,2020-05-14,470.65,SA,2752020.0,772020.0,Pieper_chat,SA,3
133,1001705,2020-05-18,38.30,LATAM,162020.0,2652020.0,EndFrame,LATAM,0
134,1001632,2020-05-30,501.76,LATAM,2162020.0,1952020.0,Hooli,LATAM,5
135,1001291,2020-05-20,247.6,LATAM,672020.0,572020.0,Riot,LATAM,2
136,1001313,2020-05-24,67.33,NZ,952020.0,1062020.0,Hooli,NZ,6
137,1001160,2020-05-15,356.47,LATAM,2252020.0,152020.0,EndFrame,LATAM,4
138,1001776,2020-05-19,309.99,LATAM,2972020.0,2562020.0,Hooli,LATAM,1
139,1001771,2020-05-07,218.80,LATAM,1952020.0,2772020.0,Pieper_chat,LATAM,3
140,1001389,2020-05-12,274.25,NZ,762020.0,2772020.0,GROW_MORE,NZ,1
141,1001602,2020-05-05,248.1,NZ,2362020.0,1552020.0,GROW_MORE,NZ,1
142,1001525,2020-05-26,531.99,NA,1572020.0,1872020.0,Hooli,NA,1
143,1001761,2020-05-27,55.22,NZ,1252020.0,1572020.0,Laxmi_Funds_25days,NZ,2
144,1001615,2020-05-13,139.25,LATAM,262020.0,552020.0,EndFrame,LATAM,2
145,1001888,2020-05-11,456.82,SA,2362020.0,952020.0,Pieper_chat,SA,0
146,1001249,2020-05-16,674.95,LATAM,572020.0,2862020.0,Laxmi_Funds_25days,LATAM,5
147,1001679,2020-05-22,908.59,SA,162020.0,1762020.0,GROW_MORE,SA,4
148,1001104,2020-05-16,648.50,NA,1372020.0,1972020.0,Pieper_chat,NA,5
149,1001892,2020-05-23,837.59,LATAM,1552020.0,2172020.0,Pieper_chat,LATAM,5
150,1001430,2020-05-09,196.72,NA,3062020.0,752020.0,Riot,NA,5
151,1001618,2020-05-28,854.80,NZ,1662020.0,1472020.0,Laxmi_Funds_25days,NZ,3
152,1001193,2020-05-26,332.45,NZ,2562020.0,1452020.0,EndFrame,NZ,1
153,1001791,2020-05-11,593.40,NA,1772020.0,172020.0,EndFrame,NA,0
154,1001242,2020-05-08,258.7,NZ,1262020.0,2872020.0,EndFrame,NZ,4
155,1001732,2020-05-30,480.91,NZ,1252020.0,362020.0,Riot,NZ,5
156,1001668,2020-05-12,552.77,NA,2962020.0,172020.0,Pieper_chat,NA,1
157,1001383,2020-05-07,293.41,LATAM,2272020.0,1362020.0,Pieper_chat,LATAM,3
158,1001336,2020-05-07,426.75,SA,2862020.0,772020.0,Hooli,SA,3
159,1001779,2020-05-18,901.10,LATAM,2452020.0,1862020.0,Riot,LATAM,0

In [66]:
val['Week_is_5']=np.where(val['Due_date'].dt.dayofweek==3,1,0)
val.head(5)

AttributeError: Can only use .dt accessor with datetimelike values

In [67]:
#Standardization of Amount Column
col_names = ['Amount($)']
features = df_1[col_names]
features1 = val[col_names]

scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
features_val = scaler.transform(features1.values)

df_1['Amount Std'] = features
val['Amount Std'] =  features_val

C:\Users\KIIT\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\KIIT\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\KIIT\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [68]:
df_1.head(5)

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area,Weekday,Amount Std
0,1001174,2020-05-24,290.98,NZ,362020.0,1062020.0,Laxmi_Funds_25days,NZ,6,-0.725205
1,1001735,2020-05-26,755.73,NA,2052020.0,172020.0,Laxmi_Funds_25days,NA,1,0.934748
2,1001719,2020-05-15,4.55,NZ,872020.0,1652020.0,Laxmi_Funds_25days,NZ,4,-1.748250
3,1001524,2020-05-01,224.61,NZ,872020.0,462020.0,GROW_MORE,NZ,4,-0.962259
4,1001427,2020-05-14,999.97,SA,1272020.0,1872020.0,EndFrame,SA,3,1.807103

In [69]:
val.head(5)

,INVOICE_NUMBER,Creation_date,Amount($),Region,Due_date,CLEARING_DATE,CUSTOMER_NAME,Business_Area,Amount Std
160,1001890,2020-05-16,953.19,SA,1952020.0,1262020.0,Hooli,SA,1.640019
161,1001343,2020-05-12,746.89,NZ,972020.0,1162020.0,Pieper_chat,NZ,0.903174
162,1001578,2020-05-09,749.30,LATAM,352020.0,1472020.0,EndFrame,LATAM,0.911782
163,1001108,2020-05-02,895.81,SA,1852020.0,2152020.0,Laxmi_Funds_25days,SA,1.435074
164,1001390,2020-05-29,228.46,SA,2252020.0,1962020.0,GROW_MORE,SA,-0.948508